In [1]:
import pandas as pd
from path import Path

In [2]:
file_path = Path('Resources/heart_clean.csv')
df_heart = pd.read_csv(file_path)
df_heart.head()

,HeartDisease,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,Asthma,KidneyDisease,SkinCancer,BMI,PhysicalHealth,MentalHealth,AgeCategory,Race,Diabetic,GenHealth,SleepTime
0,0,Yes,No,No,No,Female,Yes,Yes,No,Yes,Underweight,3,30,55-59,White,Yes,Very good,5
1,0,No,No,Yes,No,Female,Yes,No,No,No,Healthy_Weight,0,0,80 or older,White,No,Very good,7
2,0,Yes,No,No,No,Male,Yes,Yes,No,No,Overweight,20,30,65-69,White,Yes,Fair,8
3,0,No,No,No,No,Female,No,No,No,Yes,Healthy_Weight,0,0,75-79,White,No,Good,6
4,0,No,No,No,Yes,Female,Yes,No,No,No,Healthy_Weight,28,0,40-44,White,No,Very good,8

In [3]:
df_heart.corr(method ='pearson')

                HeartDisease  PhysicalHealth  MentalHealth  SleepTime
HeartDisease        1.000000        0.170721      0.028591   0.008327
PhysicalHealth      0.170721        1.000000      0.287987  -0.061387
MentalHealth        0.028591        0.287987      1.000000  -0.119717
SleepTime           0.008327       -0.061387     -0.119717   1.000000

In [5]:
#statistics summary 
df_heart.describe()

        HeartDisease  PhysicalHealth   MentalHealth      SleepTime
count  319795.000000    319795.00000  319795.000000  319795.000000
mean        0.085595         3.37171       3.898366       7.097075
std         0.279766         7.95085       7.955235       1.436007
min         0.000000         0.00000       0.000000       1.000000
25%         0.000000         0.00000       0.000000       6.000000
50%         0.000000         0.00000       0.000000       7.000000
75%         0.000000         2.00000       3.000000       8.000000
max         1.000000        30.00000      30.000000      24.000000